[package]
name = "ollama-tui-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.138"
tokio = "1.43.0"
